version: '3'
services:
  
  mt-api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: mt-api
    #restart: unless-stopped
    volumes:
      - ./api:/usr/src/api
    ports:
      - 5000:5000
    networks:
      - monetran
    depends_on:
      - db
    links:
      - db:db
    environment:
      - "ENV=dev"
      - "DB_TYPE=postgres"
      - "DB_USER=root"
      - "DB_PASS=postgres123"
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "PORT=5000"
      - "GIN_MODE=debug"
    env_file:
      - .env_dev
  

  mt-bridge:
    build: 
      context: ./bridge-service
      dockerfile: Dockerfile
    container_name: mt-bridge
    #restart: unless-stopped
    # volumes:
    #   - ./bridge-service:/usr/src/bridge
    ports:
      - 8006:8006
    networks:
      - monetran
    depends_on:
      - db
    links:
      - db:db
    environment:
      - "ENV=dev"
      - "DB_TYPE=postgres"
      - "DB_USER=root"
      - "DB_PASS=postgres123"
      - "DB_HOST=db"
      - "DB_PORT=5432"
    env_file:
      - .env_dev


  # db:
  #   image: mysql:5.7
  #   container_name: db
  #   #restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: 'monetran'
  #     MYSQL_USER: 'root'
  #     MYSQL_PASSWORD: 'root'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - '3306:3306'
  #   networks:
  #     - monetran
  #   expose:
  #     - '3306'
  #   volumes:
  #     - dbdata:/var/lib/mysql

  db:
    #image: postgres:10
    image: postgres:10-alpine
    container_name: db
    #restart: unless-stopped
    environment:
      POSTGRES_DB: 'monetran'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'postgres123'
    ports:
      - '5432:5432'
    networks:
      - monetran
    expose:
      - '5432'
    volumes:
      - dbdata:/var/lib/postgresql/data


volumes:
  dbdata:

networks:
  monetran:
    driver: bridge

