export const USER_ACTION_TYPES = {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  SIGNUP_FAILED: 'SIGNUP_FAILED',
  PASSWORD_CONFIRM_FAIL: 'PASSWORD_CONFIRM_FAIL',
  LOGIN_FAILED: 'LOGIN_FAILED',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  P2PTRANSFER_COMPLETE: 'P2PTRANSFER_COMPLETE',
  WALLET_ACTIVATED: 'WALLET_ACTIVATED',
  ACH_TRANSFER_SENT: 'ACH_TRANSFER_SENT',
  KYC_DOC_APPROVED: 'KYC_DOC_APPROVED',
  KYC_DOC_DECLINED: 'KYC_DOC_DECLINED',
  USE_2FA: 'USE_2FA',
};

export const APP_ACTION_TYPES = {
  CLEAR_FLASH_MESSAGES: 'CLEAR_FLASH_MESSAGES',
  ERROR: 'ERROR',
  ALERT: 'ALERT',
}
