apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-api-prod
  labels:
    app: mt-api-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-api-prod
  template:
    metadata:
      labels:
        app: mt-api-prod
    spec:
      containers:
        - name: nginx-proxy
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: /etc/nginx/conf.d
            subPath: nginx.conf
            name: nginx      
      containers:
        - image: gcr.io/$PROJECT_ID/monetran-backend_api-prod
          name: mt-api-prod
          env:
            - name: ENV
              value: "prod"
            - name: PORT
              value: "5000"
            - name: DB_TYPE
              value: postgres
            - name: DB_USER
              value: root
            - name: DB_PASS
              #value: postgres123
              valueFrom:
                secretKeyRef:
                  name: mysecret.prod
                  key: DB_PASS
            - name: DB_HOST
              value: "db-prod"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "monetran"
            - name: API_SECRET
              value: "MY_SECRET.prod"
            - name: APP_URL
              value: "wallet.monetran.com"
            - name: EMAIL_PORT
              value: "465"
            - name: EMAIL_FROM
              value: "do-not-reply@monetran.com"
            - name: EMAIL_ADMIN
              value: "admin@monetran.com"              
            - name: EMAIL_HOSTNAME
              value: "smtp.sendgrid.net"
            - name: EMAIL_USER
              value: "apikey"
            - name: EMAIL_PASS
              value: "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"
              # valueFrom:
              #   secretKeyRef:
              #     name: passwd
              #     key: EMAIL_PASS              
            - name: VERIFY_EMAIL_TEMP_LOC
              value: "/app/verifyemail.html"
            - name: APP_BUILD_DIR
              value: "/path/to/build"
            - name: WALLET_PUB_KEY
              value: "GATF2EUO7KVF72TPDU6XPG4V4TUZKDSSP3MB53DK5RHMRDWUKDAPYAJT"
            - name: WALLET_SEC_KEY
              #value: "SAXZGO2P2F2HZSYFVDJETJYXIQ6JOM4EW7TBBBGRPN7X6JWP5ISTSEIA"
              valueFrom:
                secretKeyRef:
                  name: mysecret.prod
                  key: WALLET_SEC_KEY
            - name: APP_FED_URL
              value: "account*wallet.monetran.com"
            - name: COWRIES_API_URL
              value: "https://api.cowrie.exchange"
            - name: PAYMENT_SRV_URL
              value: "http://mt-bridge.prod:8006/payment"
            - name: NGN_RATE
              value: "350"
            - name: APP_FEE
              value: "0.1"
            - name: NOTIFY_EMAIL
              value: "admin.monetran.com"
            - name: STELLAR_BASE_FEE
              value: "0.00001"
            - name: NGNT_WALLET_PUB_KEY
              value: ""
            - name: NGNT_WALLET_SEC_KEY
              value: ""
            - name: NGNT_ISSUER
              value: ""
            - name: STRIPE_TEST_KEY
              value: "sk_test_k76HupulGhEswhWSXTEmkq1g00G6MKi4VO"
            - name: GC_STORAGE_BUCKET
              value: "monetran-docs_prod"
            - name: GC_PROJECT_ID
              value: "flawless-point-232417"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/google_service_creds.json"
            - name: BUGSNAG_API_KEY
              value: ""
            - name: ERROR_REPORTING_CLIENT
              value: "stackdriver"
            - name: DIST_PUB_KEY
              value: "GA4JVAO2JIJCV6XNEMBG6XKKJUYGVB2HHPVOSZI4UCEXETYQ3MTL7GUS"
            - name: DIST_SEC_KEY
              #value: "SCWYNR4W6QDRPCHCQPABW6X6MGN2QKV6VOQ5DSVVKS7HMYP25UNCMVGW"
              valueFrom:
                secretKeyRef:
                  name: mysecret.prod
                  key: DIST_SEC_KEY

            - name: MNDA_ASSET_ISSUER
              value: "GBLCYS47LRXVO3I3VYB2VWH642EKKCHAC3DLMKRG2RY4RW2KRS7OYILM"
          ports:
            - containerPort: 5000
              name: mt-api-prod
          readinessProbe:
            httpGet:
              path: /ping
              port: 5000
