apiVersion: v1
kind: Service
metadata:
  name: mt-bridge-prod
  labels:
    app: mt-bridge-prod
spec:
  selector:
    app: mt-bridge-prod
  #type: ClusterIP
  type: NodePort
  ports:
    - port: 8006
