apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-bridge
  labels:
    app: mt-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-bridge
  template:
    metadata:
      labels:
        app: mt-bridge
    spec:
      containers:
        - image: gcr.io/$PROJECT_ID/monetran-backend_bridge
          name: mt-bridge
          env:
          - name: DB_NAME
            value: monetran
          - name: DB_USER
            value: "root"
          - name: DB_PASS
            value: postgres123
            # valueFrom:
            #   secretKeyRef:
            #     name: passwd
            #     key: DB_PASS
          - name: WALLET_PUB_KEY
            value: "GBTHLOH5QDMBL2J7RUVQQBEFHK7HB6UERE54XSABERJTXG4OURGEISVC"
          - name: WALLET_SEC_KEY
            value: "SAXZGO2P2F2HZSYFVDJETJYXIQ6JOM4EW7TBBBGRPN7X6JWP5ISTSEIA"
            
          ports:
            - containerPort: 8006
              name: mt-bridge
          readinessProbe:
            httpGet:
              path: /admin/
              port: 8006
          volumeMounts:
            - name: bridge-persistent-storage
              mountPath: /usr/src/bridge
      volumes:
        - name: bridge-persistent-storage
          persistentVolumeClaim:
            claimName: bridge-volumeclaim
